version: "2"
plugins:
  haxe-checkstyle:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
      MD013:
        enabled: false
      MD033:
        enabled: false

exclude_patterns:
  - "resources/"
  - "node_modules/"
  - "haxe_libraries/"
  - "haxe3_libraries/"
  - "haxe4_libraries/"
