engines:
  haxe-checkstyle:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
      MD013:
        enabled: false
      MD033:
        enabled: false

exclude_paths:
  - resources/**/*

ratings:
  paths:
    - "**.hx"
    - "**.md"