name: Haxe-Checkstyle Linux

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev
  schedule:
    - cron: '15 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        haxe-version: ['3.4.7', '4.0.5', 'nightly']
    env:
      CC_TEST_REPORTER_ID: 1dff6f89d7179dff5db635c6b4fe64acdd5694c9ed44d7da5f12f0f7d3d163b7
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Installing codeclimate client
      if: matrix.haxe-version == '4.0.5'
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Run npm install
      run: npm ci
    - name: Install Haxe version ${{ matrix.haxe-version }}
      run: |
        npx lix download haxe ${{ matrix.haxe-version }}
        npx lix use haxe ${{ matrix.haxe-version }}
    - name: Prepare Haxe 3 dependencies
      if: matrix.haxe-version == '3.4.7'
      run: |
        mv haxe_libraries haxe4_libraries
        mv haxe3_libraries haxe_libraries
    - name: Run lix download
      run: npx lix download
    - name: Fix haxeshim for "-x"
      run: ./fixHaxeshim.sh
    - name: Print versions
      run: |
        npx haxe -version
        npx neko -version
        npx haxelib list
    - name: Build neko versions
      run: |
        npx haxe build.hxml
        npx haxe buildDebug.hxml
    - name: Build NodeJs version
      run: npx haxe buildJS.hxml
    - name: Build C++ version
      run: npx haxe buildCpp.hxml
    - name: Build JSON schema
      run: npx haxe buildSchema.hxml
    - name: Run neko tests
      if: matrix.haxe-version == '3.4.7'
      run: npx haxe -D codecov_json testAndResources.hxml
    - name: Run eval tests
      if: matrix.haxe-version != '3.4.7'
      run: npx haxe -D codecov_json testAndResources.hxml
    - name: Run Java tests
      run: npx haxe testJava.hxml
    - name: Run Jvm tests
      if: matrix.haxe-version != '3.4.7'
      run: npx haxe testJvm.hxml
    - name: Format and upload codeclimate coverage
      if: success() && matrix.haxe-version == '4.0.5'
      run: |
        ( \
          cd src; \
          ../cc-test-reporter format-coverage -t lcov ../lcov.info; \
          ../cc-test-reporter upload-coverage; \
        )
    - name: Upload results to codecov
      if: success() && matrix.haxe-version == '4.0.5'
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
